Feat/missing pto endpoints
Morasiu/Clockify.Net pull request #69
Opened 2023-03-14 09:48 UTC by davidmfritz

Maybe needs some polishing but the groundwork is done. Hope you can use this in a future version in NuGet! 😺

2023-03-15 13:08 UTC, Morasiu commented
+1,698 −47 - that's a lot 😄 Thanks. I will look into it.

Also, I'll mark those tests as ignored since I don't have subscriptions or make them optional depending on the settings.

Anyway thanks for PR and let me know when it will be ready since it's marked as draft for now.

2023-03-15 13:22 UTC, davidmfritz commented on Clockify.Net/Clockify.Net.csproj
> +    <TargetFramework>netstandard2.1</TargetFramework>
Needed for Math.Clamp()

2023-03-15 14:21 UTC, davidmfritz commented
> Anyway thanks for PR and let me know when it will be ready since it's marked as draft for now.

Should be done now! Good luck with the review! 😅

2023-03-18 11:50 UTC, Morasiu requested changes

2023-03-18 11:50 UTC, Morasiu commented on Clockify.Net/Models/Holiday/DatePeriod.cs
> +public class DatePeriod {
Why is it made that way? Does my custom serialization not working? It is defined in `JsonSerializerSettings` in `ClockifyClient`.

2023-03-18 11:50 UTC, Morasiu commented on Clockify.Net/Models/TimeOff/PeriodV1Request.cs
> +	public DateTime? Start { get; set; }
Same here with DateTime. Is the serilizer not working?

2023-03-18 11:52 UTC, Morasiu commented
I also have a few changes. Checkout branch "feat/PR-69--nice-fixes"

2023-03-20 10:16 UTC, davidmfritz commented on Clockify.Net/Clockify.Net.csproj
> +    <TargetFramework>netstandard2.1</TargetFramework>
This got reset again to `netstandard2.0` and a custom `Clamp` method was instead created, because we use the package in .NET Framework.

2023-03-20 10:17 UTC, davidmfritz commented
The properties you mentioned now use a JsonSerializer and I've merged in your changes.

2023-03-20 12:06 UTC, Morasiu approved these changes

2023-04-01 14:05 UTC, Morasiu approved these changes

2023-04-01 14:05 UTC, merged

2023-04-01 14:23 UTC, Morasiu commented
Finally done! Pushed v2.3.0. Thanks @davidmfritz